### ISSUE TITLE
Tile from table missing in possible sets

### ISSUE THREAD

**Issue by JulianWgs** [gregorias/rummikubsolver#3]
Hi @gregorias,

I tried your rummikubsolver and I think I found a bug. It happened on multiple occasions, but here is one (fairly complicated) example:
![image](https://github.com/gregorias/rummikubsolver/assets/31596773/96e7e87f-fea2-423a-9175-d2ca81631745)

The red 3 and 8 in the table input are missing in the possible sets output. The suggested move is not possible.

**Comment by gregorias** [comment]
Thank you, that's interesting. I'll take a look when I get time.

**Comment by gregorias** [comment]
![grafik](https://github.com/gregorias/rummikubsolver/assets/722385/65d09f1c-e657-4ada-b166-05bfe4a71752)

I can't reproduce this exact scenario... Could you provide me with another one from one of the recent versions?

**Comment by JulianWgs** [comment]
If you can't reproduce it, it is probably fine or a very weird bug. I compiled the code via the instructions on GitHub Codespaces. I don't think it likely that the bug is coming from there. I don't know anything about the algorithm you are using. Does it matter or can it matter in which order the changes are entered into the solver. If the bug still exists, it could be triggered by a specific order. Do you use something like [quickcheck](https://hackage.haskell.org/package/QuickCheck) or other randomized testing strategies to test the code? This could be good test case to add.
If you are taking additional steps, I can't help you because my Haskell skills are rather limited. However I might do further testing in the coming days (may be reproducing this bug with another set) or test the library via the CLI using [hypothesis](https://hypothesis.readthedocs.io/en/latest/).
If you want, you can close the issue for now. I will reopen it if the need arises.
Thank you!

**Comment by gregorias** [comment]
Alright, I'm also in the process of refreshing this library and adding things like more tests, a release-to-executable process. It might be that I have prevented the bug from occurring in this particular instances.

Also, the solver may produce garbage if the table is not in a consistent state, i.e., there's no viable solution from the table alone. I intend to add an invariant for that.
